version: "3.7"

services:
  #Container principal
  app:
    #Utilizando uma imagem especifica para funcionar perfeitamente apenas com o necessário
    build:
      args:
        user: ${ARGS_USER}
        uid: ${ARGS_UID}
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - laravel
  #Servidor web - Nginx
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - laravel
  #Npm
  npm:
    image: node:20.3.1
    ports:
       - "5173:5173"
    volumes:
      - ./:/var/www
    working_dir: /var/www
    entrypoint: [ 'npm' ]
    networks:
      - laravel
networks:
  laravel:
    driver: bridge
